[package]
name = "charcam_cli"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
termion = "1.5.6"
image = "0.23.14"
charcam = { path = "../charcam" }

[dependencies.nokhwa]
version = "0.9.4"
features = ["input-v4l"]
